[build-system]
requires = ["setuptools>=61.0", "versioneer[toml]==0.29"]
build-backend = "setuptools.build_meta"

[project]
name = "tello"
authors = [
  { name="Nathan Douglas", email="Nathan20467@gmail.com" },
]
description = "A Python library implementing the Tello 1.3.0.0 SDK."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = {file = "LICENCE"}
dynamic = ["dependencies", "version"]

[project.urls]
Homepage = "https://github.com/Unoblueboy/Tello"
Issues = "https://github.com/Unoblueboy/Tello/issues"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "tello/_version.py"
versionfile_build = "tello/_version.py"
tag_prefix = ""
parentdir_prefix = ""